services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "13"
      ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234"
    volumes:
      - ~/.dockur-osx:/storage
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
